import { EventWithSubject, Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Write essay",
    description: "Write a 500-word essay on the impact of climate change.",
    status: "todo",
    priority: "HIGH",
    userId: "mock-user-1",
    deadline: new Date("2025-05-10"),
    subjectId: "math",
    projectId: null,
    parentId: null,
  },
  {
    id: "2",
    title: "Read chapter 4",
    description: "Read chapter 4 of the textbook.",
    status: "in_progress",
    priority: "MEDIUM",
    userId: "mock-user-1",
    deadline: null,
    subjectId: null,
    projectId: null,
    parentId: null,
  },
  {
    id: "3",
    title: "Submit lab report",
    description: "Submit the lab report for the chemistry experiment.",
    status: "done",
    priority: "LOW",
    userId: "mock-user-1",
    deadline: new Date("2025-05-01"),
    subjectId: "bio",
    projectId: null,
    parentId: null,
  },
  {
    id: "4",
    title: "Prepare presentation",
    description: "Cover slides 1-10, include diagrams",
    status: "in-progress",
    priority: "HIGH",
    userId: "mock-user-1",
    deadline: new Date("2025-05-15"),
    projectId: "project-1",
    subjectId: "math",
    parentId: "1",
  },
];

// Mock event — replace with: const response = await getNextEvent()
const mockNextEvent: EventWithSubject = {
  id: "event-1",
  title: "Data Structures",
  description: "Lecture with Prof. Aris • Room 302",
  startTime: new Date(new Date().setHours(new Date().getHours() + 1, 30, 0, 0)),
  endTime: new Date(new Date().setHours(new Date().getHours() + 3, 0, 0, 0)),
  isRecurring: true,
  recurrenceRule: null,
  userId: "mock-user-1",
  subjectId: "subject-1",
  subject: {
    id: "subject-1",
    name: "Data Structures",
    credits: 4,
    color: "#3b82f6",
    userId: "mock-user-1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};
